# Generated by Django 5.1.1 on 2024-11-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tskApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
