# Generated by Django 5.1.1 on 2024-11-20 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tskApp', '0002_remove_task_created_at_remove_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timer',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
